[2024-09-27T22:27:28.505+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-27T22:27:28.545+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_share_prices_with_company_data.save_share_prices_data scheduled__2023-12-24T00:00:00+00:00 [queued]>
[2024-09-27T22:27:28.601+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_share_prices_with_company_data.save_share_prices_data scheduled__2023-12-24T00:00:00+00:00 [queued]>
[2024-09-27T22:27:28.605+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-09-27T22:27:28.686+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): save_share_prices_data> on 2023-12-24 00:00:00+00:00
[2024-09-27T22:27:28.702+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=55) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-27T22:27:28.724+0000] {standard_task_runner.py:72} INFO - Started process 87 to run task
[2024-09-27T22:27:28.742+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_share_prices_with_company_data', 'save_share_prices_data', 'scheduled__2023-12-24T00:00:00+00:00', '--job-id', '2591', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpsqwv3pmx']
[2024-09-27T22:27:28.759+0000] {standard_task_runner.py:105} INFO - Job 2591: Subtask save_share_prices_data
[2024-09-27T22:27:29.923+0000] {task_command.py:467} INFO - Running <TaskInstance: scrape_and_save_share_prices_with_company_data.save_share_prices_data scheduled__2023-12-24T00:00:00+00:00 [running]> on host 7746de5121f6
[2024-09-27T22:27:30.742+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scrape_and_save_share_prices_with_company_data' AIRFLOW_CTX_TASK_ID='save_share_prices_data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-24T00:00:00+00:00'
[2024-09-27T22:27:30.749+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-27T22:27:30.751+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-27T22:27:30.752+0000] {logging_mixin.py:190} INFO - Current task name:save_share_prices_data state:running start_date:2024-09-27 22:27:28.565264+00:00
[2024-09-27T22:27:30.753+0000] {logging_mixin.py:190} INFO - Dag name:scrape_and_save_share_prices_with_company_data and current dag run status:running
[2024-09-27T22:27:30.756+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-27T22:27:47.048+0000] {base.py:84} INFO - Retrieving connection 'dse_connection'
[2024-09-27T22:27:47.865+0000] {job.py:229} INFO - Heartbeat recovered after 14.01 seconds
[2024-09-27T22:28:08.096+0000] {logging_mixin.py:190} INFO - Error inserting share prices data: connection to server at "172.26.0.3", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-09-27T22:28:08.105+0000] {base.py:84} INFO - Retrieving connection 'dse_connection'
[2024-09-27T22:28:29.141+0000] {logging_mixin.py:190} INFO - Error inserting share prices data: connection to server at "172.26.0.3", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-09-27T22:28:29.150+0000] {base.py:84} INFO - Retrieving connection 'dse_connection'
[2024-09-27T22:28:50.193+0000] {logging_mixin.py:190} INFO - Error inserting share prices data: connection to server at "172.26.0.3", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-09-27T22:28:50.210+0000] {base.py:84} INFO - Retrieving connection 'dse_connection'
[2024-09-27T22:29:11.260+0000] {logging_mixin.py:190} INFO - Error inserting share prices data: connection to server at "172.26.0.3", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-09-27T22:29:11.270+0000] {base.py:84} INFO - Retrieving connection 'dse_connection'
[2024-09-27T22:29:32.308+0000] {logging_mixin.py:190} INFO - Error inserting share prices data: connection to server at "172.26.0.3", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-09-27T22:29:32.316+0000] {base.py:84} INFO - Retrieving connection 'dse_connection'
[2024-09-27T22:29:53.612+0000] {logging_mixin.py:190} INFO - Error inserting share prices data: connection to server at "172.26.0.3", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-09-27T22:29:53.654+0000] {base.py:84} INFO - Retrieving connection 'dse_connection'
[2024-09-27T22:30:12.713+0000] {job.py:229} INFO - Heartbeat recovered after 11.85 seconds
[2024-09-27T22:30:15.103+0000] {logging_mixin.py:190} INFO - Error inserting share prices data: connection to server at "172.26.0.3", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-09-27T22:30:15.658+0000] {base.py:84} INFO - Retrieving connection 'dse_connection'
[2024-09-27T22:30:19.254+0000] {job.py:229} INFO - Heartbeat recovered after 12.43 seconds
[2024-09-27T22:30:36.764+0000] {logging_mixin.py:190} INFO - Error inserting share prices data: connection to server at "172.26.0.3", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-09-27T22:30:36.773+0000] {base.py:84} INFO - Retrieving connection 'dse_connection'
[2024-09-27T22:30:57.805+0000] {logging_mixin.py:190} INFO - Error inserting share prices data: connection to server at "172.26.0.3", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-09-27T22:30:57.814+0000] {base.py:84} INFO - Retrieving connection 'dse_connection'
[2024-09-27T22:31:18.853+0000] {logging_mixin.py:190} INFO - Error inserting share prices data: connection to server at "172.26.0.3", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-09-27T22:31:18.862+0000] {base.py:84} INFO - Retrieving connection 'dse_connection'
[2024-09-27T22:31:39.904+0000] {logging_mixin.py:190} INFO - Error inserting share prices data: connection to server at "172.26.0.3", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-09-27T22:31:39.914+0000] {base.py:84} INFO - Retrieving connection 'dse_connection'
[2024-09-27T22:31:50.579+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-09-27T22:31:50.580+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-27T22:31:50.583+0000] {process_utils.py:132} INFO - Sending 15 to group 87. PIDs of all processes in the group: [87]
[2024-09-27T22:31:50.584+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 87
[2024-09-27T22:32:00.965+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-27T22:32:01.006+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-27T22:32:01.099+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=87, status='terminated', exitcode=0, started='22:27:27') (87) terminated with exit code 0
[2024-09-27T22:32:01.431+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
