[2024-09-27T18:29:00.122+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-27T18:29:00.308+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_share_prices_with_company_data.save_share_prices_data scheduled__2023-11-01T00:00:00+00:00 [queued]>
[2024-09-27T18:29:00.352+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_share_prices_with_company_data.save_share_prices_data scheduled__2023-11-01T00:00:00+00:00 [queued]>
[2024-09-27T18:29:00.364+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-09-27T18:29:00.445+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): save_share_prices_data> on 2023-11-01 00:00:00+00:00
[2024-09-27T18:29:00.484+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=13399) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-27T18:29:00.494+0000] {standard_task_runner.py:72} INFO - Started process 13421 to run task
[2024-09-27T18:29:00.493+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_share_prices_with_company_data', 'save_share_prices_data', 'scheduled__2023-11-01T00:00:00+00:00', '--job-id', '1460', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpongeus5i']
[2024-09-27T18:29:00.504+0000] {standard_task_runner.py:105} INFO - Job 1460: Subtask save_share_prices_data
[2024-09-27T18:29:00.787+0000] {task_command.py:467} INFO - Running <TaskInstance: scrape_and_save_share_prices_with_company_data.save_share_prices_data scheduled__2023-11-01T00:00:00+00:00 [running]> on host 13b5797a93ab
[2024-09-27T18:29:01.495+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scrape_and_save_share_prices_with_company_data' AIRFLOW_CTX_TASK_ID='save_share_prices_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-01T00:00:00+00:00'
[2024-09-27T18:29:01.500+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-27T18:29:01.501+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-27T18:29:01.504+0000] {logging_mixin.py:190} INFO - Current task name:save_share_prices_data state:running start_date:2024-09-27 18:29:00.325737+00:00
[2024-09-27T18:29:01.508+0000] {logging_mixin.py:190} INFO - Dag name:scrape_and_save_share_prices_with_company_data and current dag run status:running
[2024-09-27T18:29:01.510+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-27T18:29:10.066+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 112, in save_share_prices_data
    extracted_rows = extract_share_data()
                     ^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 43, in extract_share_data
    for tr in table.find_all('tr'):
              ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_all'
[2024-09-27T18:29:10.391+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-27T18:29:10.394+0000] {logging_mixin.py:190} INFO - Task start:2024-09-27 18:29:00.325737+00:00 end:2024-09-27 18:29:10.389231+00:00 duration:10.063494
[2024-09-27T18:29:10.395+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): save_share_prices_data> dag:<DAG: scrape_and_save_share_prices_with_company_data> dagrun:<DagRun scrape_and_save_share_prices_with_company_data @ 2023-11-01 00:00:00+00:00: scheduled__2023-11-01T00:00:00+00:00, state:running, queued_at: 2024-09-27 18:13:40.307318+00:00. externally triggered: False>
[2024-09-27T18:29:10.403+0000] {logging_mixin.py:190} INFO - Failure caused by 'NoneType' object has no attribute 'find_all'
[2024-09-27T18:29:10.409+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=scrape_and_save_share_prices_with_company_data, task_id=save_share_prices_data, run_id=scheduled__2023-11-01T00:00:00+00:00, execution_date=20231101T000000, start_date=20240927T182900, end_date=20240927T182910
[2024-09-27T18:29:10.429+0000] {job.py:229} INFO - Heartbeat recovered after 10.73 seconds
[2024-09-27T18:29:10.475+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-27T18:29:10.503+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1460 for task save_share_prices_data ('NoneType' object has no attribute 'find_all'; 13421)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 112, in save_share_prices_data
    extracted_rows = extract_share_data()
                     ^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 43, in extract_share_data
    for tr in table.find_all('tr'):
              ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_all'
[2024-09-27T18:29:10.781+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-27T18:29:10.941+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-27T18:29:10.962+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
