[2024-09-27T18:41:33.430+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-27T18:41:33.507+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_share_prices_with_company_data.extract_and_save_company_basic_data scheduled__2024-02-09T00:00:00+00:00 [queued]>
[2024-09-27T18:41:33.567+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_share_prices_with_company_data.extract_and_save_company_basic_data scheduled__2024-02-09T00:00:00+00:00 [queued]>
[2024-09-27T18:41:33.570+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-27T18:41:33.628+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_and_save_company_basic_data> on 2024-02-09 00:00:00+00:00
[2024-09-27T18:41:33.667+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=14342) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-27T18:41:33.736+0000] {standard_task_runner.py:72} INFO - Started process 14355 to run task
[2024-09-27T18:41:33.671+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_share_prices_with_company_data', 'extract_and_save_company_basic_data', 'scheduled__2024-02-09T00:00:00+00:00', '--job-id', '1663', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpfujce4n5']
[2024-09-27T18:41:33.756+0000] {standard_task_runner.py:105} INFO - Job 1663: Subtask extract_and_save_company_basic_data
[2024-09-27T18:41:34.077+0000] {task_command.py:467} INFO - Running <TaskInstance: scrape_and_save_share_prices_with_company_data.extract_and_save_company_basic_data scheduled__2024-02-09T00:00:00+00:00 [running]> on host 13b5797a93ab
[2024-09-27T18:41:34.556+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scrape_and_save_share_prices_with_company_data' AIRFLOW_CTX_TASK_ID='extract_and_save_company_basic_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-09T00:00:00+00:00'
[2024-09-27T18:41:34.567+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-27T18:41:34.580+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-27T18:41:34.581+0000] {logging_mixin.py:190} INFO - Current task name:extract_and_save_company_basic_data state:running start_date:2024-09-27 18:41:33.514300+00:00
[2024-09-27T18:41:34.584+0000] {logging_mixin.py:190} INFO - Dag name:scrape_and_save_share_prices_with_company_data and current dag run status:running
[2024-09-27T18:41:34.587+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-27T18:41:34.658+0000] {base.py:84} INFO - Retrieving connection 'dse_connection'
[2024-09-27T18:41:34.698+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 143, in extract_and_save_company_basic_data
    companies = company_list()
                ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 136, in company_list
    cursor.execute(sql_query)
psycopg2.errors.UndefinedTable: relation "company_list" does not exist
LINE 1: SELECT * FROM company_list
                      ^

[2024-09-27T18:41:34.784+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-27T18:41:34.786+0000] {logging_mixin.py:190} INFO - Task start:2024-09-27 18:41:33.514300+00:00 end:2024-09-27 18:41:34.783783+00:00 duration:1.269483
[2024-09-27T18:41:34.790+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_and_save_company_basic_data> dag:<DAG: scrape_and_save_share_prices_with_company_data> dagrun:<DagRun scrape_and_save_share_prices_with_company_data @ 2024-02-09 00:00:00+00:00: scheduled__2024-02-09T00:00:00+00:00, state:running, queued_at: 2024-09-27 18:39:44.977118+00:00. externally triggered: False>
[2024-09-27T18:41:34.794+0000] {logging_mixin.py:190} INFO - Failure caused by relation "company_list" does not exist
LINE 1: SELECT * FROM company_list
                      ^
[2024-09-27T18:41:34.799+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=scrape_and_save_share_prices_with_company_data, task_id=extract_and_save_company_basic_data, run_id=scheduled__2024-02-09T00:00:00+00:00, execution_date=20240209T000000, start_date=20240927T184133, end_date=20240927T184134
[2024-09-27T18:41:34.854+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-27T18:41:34.857+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1663 for task extract_and_save_company_basic_data (relation "company_list" does not exist
LINE 1: SELECT * FROM company_list
                      ^
; 14355)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 143, in extract_and_save_company_basic_data
    companies = company_list()
                ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 136, in company_list
    cursor.execute(sql_query)
psycopg2.errors.UndefinedTable: relation "company_list" does not exist
LINE 1: SELECT * FROM company_list
                      ^

[2024-09-27T18:41:34.921+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-27T18:41:35.046+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-27T18:41:35.072+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
