[2024-09-27T18:52:04.799+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-27T18:52:04.817+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_share_prices_with_company_data.extract_and_save_company_basic_data manual__2024-09-27T18:43:07.996616+00:00 [queued]>
[2024-09-27T18:52:04.827+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_share_prices_with_company_data.extract_and_save_company_basic_data manual__2024-09-27T18:43:07.996616+00:00 [queued]>
[2024-09-27T18:52:04.828+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-09-27T18:52:04.843+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_and_save_company_basic_data> on 2024-09-27 18:43:07.996616+00:00
[2024-09-27T18:52:04.850+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=14822) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-27T18:52:04.852+0000] {standard_task_runner.py:72} INFO - Started process 14826 to run task
[2024-09-27T18:52:04.853+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_share_prices_with_company_data', 'extract_and_save_company_basic_data', 'manual__2024-09-27T18:43:07.996616+00:00', '--job-id', '1751', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp2kj1b6fp']
[2024-09-27T18:52:04.855+0000] {standard_task_runner.py:105} INFO - Job 1751: Subtask extract_and_save_company_basic_data
[2024-09-27T18:52:04.907+0000] {task_command.py:467} INFO - Running <TaskInstance: scrape_and_save_share_prices_with_company_data.extract_and_save_company_basic_data manual__2024-09-27T18:43:07.996616+00:00 [running]> on host 13b5797a93ab
[2024-09-27T18:52:05.013+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scrape_and_save_share_prices_with_company_data' AIRFLOW_CTX_TASK_ID='extract_and_save_company_basic_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-27T18:43:07.996616+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-27T18:43:07.996616+00:00'
[2024-09-27T18:52:05.015+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-27T18:52:05.016+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-27T18:52:05.016+0000] {logging_mixin.py:190} INFO - Current task name:extract_and_save_company_basic_data state:running start_date:2024-09-27 18:52:04.818401+00:00
[2024-09-27T18:52:05.017+0000] {logging_mixin.py:190} INFO - Dag name:scrape_and_save_share_prices_with_company_data and current dag run status:running
[2024-09-27T18:52:05.018+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-27T18:52:05.028+0000] {base.py:84} INFO - Retrieving connection 'dse_connection'
[2024-09-27T18:52:05.034+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 143, in extract_and_save_company_basic_data
    companies = company_list()
                ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 136, in company_list
    cursor.execute(sql_query)
psycopg2.errors.UndefinedTable: relation "company_list" does not exist
LINE 1: SELECT * FROM company_list
                      ^

[2024-09-27T18:52:05.051+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-27T18:52:05.052+0000] {logging_mixin.py:190} INFO - Task start:2024-09-27 18:52:04.818401+00:00 end:2024-09-27 18:52:05.050780+00:00 duration:0.232379
[2024-09-27T18:52:05.052+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_and_save_company_basic_data> dag:<DAG: scrape_and_save_share_prices_with_company_data> dagrun:<DagRun scrape_and_save_share_prices_with_company_data @ 2024-09-27 18:43:07.996616+00:00: manual__2024-09-27T18:43:07.996616+00:00, state:running, queued_at: 2024-09-27 18:43:08.012682+00:00. externally triggered: True>
[2024-09-27T18:52:05.053+0000] {logging_mixin.py:190} INFO - Failure caused by relation "company_list" does not exist
LINE 1: SELECT * FROM company_list
                      ^
[2024-09-27T18:52:05.054+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=scrape_and_save_share_prices_with_company_data, task_id=extract_and_save_company_basic_data, run_id=manual__2024-09-27T18:43:07.996616+00:00, execution_date=20240927T184307, start_date=20240927T185204, end_date=20240927T185205
[2024-09-27T18:52:05.075+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-27T18:52:05.076+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1751 for task extract_and_save_company_basic_data (relation "company_list" does not exist
LINE 1: SELECT * FROM company_list
                      ^
; 14826)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 143, in extract_and_save_company_basic_data
    companies = company_list()
                ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 136, in company_list
    cursor.execute(sql_query)
psycopg2.errors.UndefinedTable: relation "company_list" does not exist
LINE 1: SELECT * FROM company_list
                      ^

[2024-09-27T18:52:05.108+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-27T18:52:05.131+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-27T18:52:05.136+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
